import { StyleSheet, Platform } from 'react-native';
import { theme } from '../theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.background.primary,
  },
  container: {
    flex: 1,
  },
  header: {
    padding: theme.spacing.medium,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  headerTitle: {
    fontSize: theme.typography.fontSize.large,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.white,
  },
  content: {
    flex: 1,
    padding: theme.spacing.medium,
  },
  section: {
    marginBottom: theme.spacing.xlarge,
    padding: 16,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    overflow: 'hidden',
  },
  sectionTitle: {
    fontSize: theme.typography.fontSize.medium,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.white,
    marginBottom: theme.spacing.small,
  },
  sectionDescription: {
    fontSize: theme.typography.fontSize.small,
    color: theme.colors.gray.light,
    marginBottom: theme.spacing.medium,
  },
  durationContainer: {
    borderRadius: theme.borders.radius.medium,
    //padding: theme.spacing.small,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  durationInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'flex-start',
    borderRadius: theme.borders.radius.medium,
    padding: theme.spacing.small,
    flex: 1,
    marginRight: 16,
  },
  durationInput: {
    fontSize: theme.typography.fontSize.large,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.white,
    width: 80,
    textAlign: 'center',
  },
  durationUnit: {
    fontSize: theme.typography.fontSize.small,
    color: theme.colors.gray.light,
    marginLeft: theme.spacing.small,
  },
  durationControls: {
    flexDirection: 'row',
    gap: 8,
  },
  durationButton: {
    width: 44,
    height: 44,
    borderRadius: theme.borders.radius.round,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  testButtonActive: {
    backgroundColor: '#f44336',
  },
  testButtonText: {
    color: '#eee',
    fontWeight: '500',
  },
  vibrationProgressContainer: {
    marginTop: 16,
  },
  vibrationProgressBar: {
    height: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 4,
    overflow: 'hidden',
  },
  vibrationProgressFill: {
    height: '100%',
    backgroundColor: '#f44336',
  },
  vibrationProgressText: {
    color: '#aaa',
    fontSize: 12,
    marginTop: 4,
    textAlign: 'center',
  },
  alertItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: theme.borders.radius.medium,
    padding: theme.spacing.medium,
    marginBottom: theme.spacing.small,
  },
  alertInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  alertTextContainer: {
    marginLeft: theme.spacing.medium,
    flex: 1,
  },
  alertName: {
    fontSize: theme.typography.fontSize.medium,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.white,
  },
  alertDetail: {
    fontSize: theme.typography.fontSize.small,
    color: theme.colors.gray.light,
    marginTop: theme.spacing.xs,
  },
  alertControls: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  editButton: {
    width: 44,
    height: 44,
    borderRadius: theme.borders.radius.round,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  hiddenCamera: {
    width: 1,
    height: 1,
    opacity: 0,
    position: 'absolute',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  emptyStateText: {
    color: '#aaa',
    fontSize: 16,
    fontWeight: '600',
    marginTop: 12,
  },
  emptyStateSubtext: {
    color: '#888',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 8,
  },
  soundsList: {
    maxHeight: 200,
  },
  soundsListContent: {
    paddingVertical: 8,
  },
  soundItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  soundInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  soundName: {
    color: '#eee',
    fontSize: 14,
    marginLeft: 12,
    flex: 1,
  },
  deleteButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addSoundButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
    padding: 12,
    marginTop: 12,
  },
  addSoundButtonText: {
    color: '#eee',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 8,
  },
  timeDisplayContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: theme.borders.radius.medium,
    padding: theme.spacing.medium,
  },
  timeDisplayButton: {
    flex: 1,
  },
  confirmButton: {
    width: 44,
    height: 44,
    borderRadius: theme.borders.radius.round,
    backgroundColor: theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: theme.spacing.medium,
  },
});